Repository Team-Ampersand/Gmu-WiKi-client-v3, pull requests merged in 2023-08, with the labels that each got.

#2 🔀 Header 퍼블리싱
  src/assets/.gitkeep
  src/assets/svg/.gitkeep
  src/assets/svg/Etc.tsx
  src/assets/svg/Logo.tsx
  src/assets/svg/Notice.tsx
  src/assets/svg/School.tsx
  src/assets/svg/Search.tsx
  src/assets/svg/index.ts
  src/components/Header/DropMenu/index.tsx
  src/components/Header/DropMenu/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/common/.gitkeep
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
  src/styles/globals.tsx
  src/types/.gitkeep
  src/types/components/DropMenuPropsTypes.ts
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#3 Revert 2 feature/header
  src/pages/_document.tsx
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#6 🔀 favicon과 title 설정
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/components/SEO/index.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/types/components/SEOPropsType.ts
Labels: 2️⃣ Priortiy: Medium, 🪛 Type: Performance

#7 🔀 Footer 추가
  src/components/Footer/index.tsx
  src/components/Footer/style.ts
  src/pages/_app.tsx
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#8 🔀 버튼 컴포넌트 추가
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/common/.gitkeep
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
  src/types/components/common/ButtonProps.ts
Labels: 3️⃣ Priority: Low, 🪛 Type: Performance

#9 🔀최근 수정된 글 퍼블리싱
  package.json
  public/fonts/woff/Pretendard-Black.woff
  public/fonts/woff/Pretendard-Bold.woff
  public/fonts/woff/Pretendard-ExtraBold.woff
  public/fonts/woff/Pretendard-ExtraLight.woff
  public/fonts/woff/Pretendard-Light.woff
  public/fonts/woff/Pretendard-Medium.woff
  public/fonts/woff/Pretendard-Regular.woff
  public/fonts/woff/Pretendard-SemiBold.woff
  public/fonts/woff/Pretendard-Thin.woff
  public/fonts/woff2/Pretendard-Black.woff2
  public/fonts/woff2/Pretendard-Bold.woff2
  public/fonts/woff2/Pretendard-ExtraBold.woff2
  public/fonts/woff2/Pretendard-ExtraLight.woff2
  public/fonts/woff2/Pretendard-Light.woff2
  public/fonts/woff2/Pretendard-Medium.woff2
  public/fonts/woff2/Pretendard-Regular.woff2
  public/fonts/woff2/Pretendard-SemiBold.woff2
  public/fonts/woff2/Pretendard-Thin.woff2
  src/apis/.gitkeep
  src/apis/EnvConfig.ts
  src/apis/index.ts
  src/components/RecentModified/index.tsx
  src/components/RecentModified/style.ts
  src/hooks/index.tsx
  src/hooks/useFetch.tsx
  src/pages/home.tsx
  src/types/components/RecentListType.ts
  src/types/hooks/useFetchOptionsType.ts
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#10 🔀 Header & DropMenu UI
  src/assets/svg/Etc.tsx
  src/assets/svg/Logo.tsx
  src/assets/svg/Notice.tsx
  src/assets/svg/School.tsx
  src/assets/svg/Search.tsx
  src/assets/svg/index.ts
  src/components/Header/DropMenu/index.tsx
  src/components/Header/DropMenu/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.tsx
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#11 🔀 RecentModified 구조 개선
  src/components/RecentModified/index.tsx
  src/components/RecentModified/style.ts
Labels: 2️⃣ Priortiy: Medium, 🪛 Type: Performance

#12 🔀 page container 컴포넌트 퍼블리싱
  src/components/common/PageContainer/index.tsx
  src/components/common/PageContainer/style.ts
  src/pages/_app.tsx
  src/pages/home.tsx
  src/types/components/PageContainerPropsType.ts
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing
